{{- if .Values.core.enabled }}
{{- with .Values.core }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jumpserver.fullname" $ }}-core
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
type: Opaque
data:
  secret-key: {{ default (include "getValueFromSecret" (dict "Namespace" $.Release.Namespace "Kind" "Secret" "Name" (print $.Release.Name "-core") "Key" "secret-key" "Length" 50) | b64enc | quote) .config.secretKey }}
  bootstrap-token: {{ default (include "getValueFromSecret" (dict "Namespace" $.Release.Namespace "Kind" "Secret" "Name" (print $.Release.Name "-core") "Key" "bootstrap-token" "Length" 24) | b64enc | quote) .config.bootstrapToken }}
{{- end }}
{{- end }}
