apiVersion: v1
name: jumpserver
version: 2.25.2
appVersion: "v2.25.2"
description: A Helm chart for Deploying Jumpserver on Kubernetes
engine: gotpl
home: https://jumpserver.org
icon: https://jumpserver.org/images/logo/favicon.ico
maintainers:
- email: support@fit2cloud.com
  name: jumpserver
sources:
- https://github.com/jumpserver/
type: application
dependencies:
- name: mysql
  version: 8.8.34
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: redis
  version: 16.4.5
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
